name: Bazel

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win64
            architecture: x64
          - os: macos-latest
            artifact-name: macOS
            architecture: x64
          - os: ubuntu-latest
            artifact-name: Linux
            architecture: x64

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: bazelbuild/setup-bazelisk@v1

      - name: Build
        run: bazel test ... --nojava_header_compilation -k
        shell: bash